on:
  workflow_dispatch:
    inputs:
      version: ""
      sha256: ""

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Edit ruby file
        run: |
          sed -i -E -z "s/[0-9]\.[0-9]\.[0-9]/${{ inputs.version }}/g" ./crock.rb
          sed -i -E -z "s/[0-9a-f]{64}/${{ inputs.sha256 }}/g" ./crock.rb

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.PAT }}
